---
- hosts: all

  vars_files:
    - default.config.yml

  handlers:
    - name: Add ssh passphrase
      command: ssh-keygen -p -f "{{ home_directory }}/.ssh/id_rsa"

    - name: Setup ssh-agent
      shell: eval "$(ssh-agent -s)" && ssh-add -K "{{ home_directory }}/.ssh/id_rsa"

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
    - import_tasks: tasks/zsh/zsh.yml
      tags: ['zsh']

    - import_tasks: tasks/macos/macos.yml
      when: configure_macos
      tags: ['macos']

    - import_tasks: tasks/dotfiles/dotfiles.yml
      tags: ['dotfiles']

    - import_tasks: tasks/ssh/ssh.yml
      tags: ['ssh']

    - import_tasks: tasks/git/git.yml
      tags: ['git']

    - import_tasks: tasks/scripts/scripts.yml
      tags: ['scripts']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: Comcast.sdkman
    - role: markosamuli.nvm

  tasks:
    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
