---
# getting my dotfile configuration

- name: Copy in git config
  template: src=tasks/git/templates/gitconfig dest={{home_directory}}/.gitconfig

- name: Copy in global git ignore
  copy: src=files/dotfiles/gitignore_global dest={{home_directory}}/.gitignore_global

- name: Copy in gitcloneenv
  template: src=tasks/git/templates/gitcloneenv dest={{home_directory}}/.gitcloneenv
