---

- name: Ensure presence of .ssh
  file: state=directory recurse=yes path={{ home_directory }}/.ssh

- name: Copy in .ssh/config
  copy: src=tasks/ssh/config dest={{ home_directory }}/.ssh/config

- name: Create SSH Key
  openssh_keypair:
    path: "{{ home_directory }}/.ssh/id_rsa"
    comment: "{{ email }}"
  notify:
    - Add ssh passphrase
    - Setup ssh-agent
