---
# getting my dotfile configuration

- name: Initialise brew & zsh completion in .zprofile
  blockinfile:
    path: "{{ home_directory }}/.zprofile"
    create: yes
    insertbefore: BOF
    block: |
      eval "$(/opt/homebrew/bin/brew shellenv)"

      if type brew &>/dev/null
      then
        FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
      fi

- name: Initialise .zshrc
  blockinfile:
    path: "{{ home_directory }}/.zshrc"
    create: yes
    insertbefore: BOF
    block: |
      autoload -Uz compinit
      compinit

      if type brew &>/dev/null && [ -f "$(brew --prefix)/etc/bash_completion.d/git-prompt.sh" ]; then
        GIT_PS1_SHOWCOLORHINTS=true
        GIT_PS1_SHOWUPSTREAM=auto
        GIT_PS1_SHOWDIRTYSTATE=true
        GIT_PS1_SHOWUNTRACKEDFILES=true
        GIT_PS1_SHOWSTASHSTATE=true
  
        source "$(brew --prefix)/etc/bash_completion.d/git-prompt.sh"
        setopt PROMPT_SUBST ; PS1='%~$(__git_ps1 " (%s)")%(?..%F{red}[%?] )%f\$ '
      else
        setopt PROMPT_SUBST ; PS1='%~%(?..%F{red}[%?] )%f\$ '
      fi
      
      alias ll='ls -lAh'
      
      export JAVA_OPTS="$JAVA_OPTS -Dapple.awt.UIElement=true"
